### ISSUE TITLE
Image features

### ISSUE THREAD

**Issue by Mingxiao-Li** [zipengxuc/ADVSE-GuessWhat#1]
Hi, did you extract the faster-rcnn image featuere by yourself or you find this feature in somewhere?

**Comment by zipengxuc** [comment]
> Hi, did you extract the faster-rcnn image featuere by yourself or you find this feature in somewhere?

Hi, thanks for the question. The faster-rcnn image feature is downloaded from: [https://github.com/peteanderson80/bottom-up-attention](https://github.com/peteanderson80/bottom-up-attention) and is transformed into two files, i.e. 
 size,rcnn_arch,224.hy and size,rcnn_arch,224.txt.

size, rcnn_arch,224.hy contains ALL image features of the shape: (204721, 36, 2048).
size, rcnn_arch,224.txt contains ALL corresponding image filenames.

**Comment by Mingxiao-Li** [comment]
> > Hi, did you extract the faster-rcnn image featuere by yourself or you find this feature in somewhere?
> 
> Hi, thanks for the question. The faster-rcnn image feature is downloaded from: https://github.com/peteanderson80/bottom-up-attention and is transformed into two files, i.e.
> size,rcnn_arch,224.hy and size,rcnn_arch,224.txt.
> 
> size, rcnn_arch,224.hy contains ALL image features of the shape: (204721, 36, 2048).
> size, rcnn_arch,224.txt contains ALL corresponding image filenames.

Many thanks for your quicky reply.

**Comment by Mingxiao-Li** [comment]
Hi, Could you share the guess what dataset ? The original link to download the guesswhat dataset doesn't work anymore. Thanks in advance.

**Comment by Mingxiao-Li** [comment]
> > Hi, did you extract the faster-rcnn image featuere by yourself or you find this feature in somewhere?
> 
> Hi, thanks for the question. The faster-rcnn image feature is downloaded from: https://github.com/peteanderson80/bottom-up-attention and is transformed into two files, i.e.
> size,rcnn_arch,224.hy and size,rcnn_arch,224.txt.
> 
> size, rcnn_arch,224.hy contains ALL image features of the shape: (204721, 36, 2048).
> size, rcnn_arch,224.txt contains ALL corresponding image filenames.

Hi，I download the image features (36 feature per image) from the link you mention, but I found there are less or more than 36 features in many images. Did you also use this version, or you use the verison with 100 feature per image ?
